fos_ck_editor:
    default_config: news
    toolbars:
        configs:
            news_post_toolbar: [ "@document", "-", "@clipboard", "-", "@undo", "-", "@editing" , "-", "@basicstyles", "-", "@paragraph", "-", "@insert", '-', "@colors", "-", "@tool", "/", "@styles"]
        items:
            document: [ "Preview", "Print" ]
            clipboard: ["Cut", "Copy", "Paste", "PasteText", "PasteFromWord"]
            undo: ["Undo", "Redo"]
            editing: ["Find", "Replace","SelectAll", "SpellCheck"]
            basicstyles: ["Bold", "Italic", "Underline", "Strikethrough", "Subscript", "Superscript", "CopyFormatting", "RemoveFormat"]
            paragraph: ["NumberedList", "BulletedList", "Outdent", "Indent", "Blockquote", "JustifyLeft", "JustifyCenter", "JustifyRight", "JustifyBlock", "Link", "Unlink"]
            insert: ['Image', "HorizontalRule"]
            colors: ['TextColor']
            tool:     [ "Maximize" ]
            styles: ["Styles", "Format", "FontSize"]
    configs:
        news: 
            # default toolbar plus Format button
            toolbar: "news_post_toolbar"
            # - [Bold, Italic, Underline, -, Cut, Copy, Paste,
            #   PasteText, PasteFromWord, -, Undo, Redo, -,
            #   NumberedList, BulletedList, -, Outdent, Indent, -,
            #   Blockquote, -, Image, Link, Unlink, Table]
            # - [Format, Maximize, Source]

            filebrowserBrowseRoute: admin_sonata_media_media_ckeditor_browser
            filebrowserImageBrowseRoute: admin_sonata_media_media_ckeditor_browser
            # Display images by default when clicking the image dialog browse button
            filebrowserImageBrowseRouteParameters:
                provider: sonata.media.provider.image
            filebrowserUploadMethod: form
            filebrowserUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserUploadRouteParameters:
                provider: sonata.media.provider.file
            # Upload file as image when sending a file from the image dialog
            filebrowserImageUploadRoute: admin_sonata_media_media_ckeditor_upload
            filebrowserImageUploadRouteParameters:
                provider: sonata.media.provider.image
                context: my-context # Optional, to upload in a custom context
                format: my-big # Optional, media format or original size returned to editor