sonata_user:
    class:
        user:
            # Application\Sonata\UserBundle\Entity\User
            App\Entity\User\AdminUser
        group:
            Application\Sonata\UserBundle\Entity\Group