sonata_media:
    class:
        media: Application\Sonata\MediaBundle\Entity\Media
        gallery: Application\Sonata\MediaBundle\Entity\Gallery
        gallery_has_media: Application\Sonata\MediaBundle\Entity\GalleryHasMedia
        category: Application\Sonata\ClassificationBundle\Entity\Category

    force_disable_category: true # true, if you really want to disable the relation with category
    category_manager:       null # null or "sonata.media.manager.category.default" if classification bundle exists
    db_driver: doctrine_orm
    default_context: news
    contexts:
        default:
            providers:
                - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
                - sonata.media.provider.file
                - sonata.media.provider.vimeo

            formats:
                small: { width: 100 , quality: 70}
                big:   { width: 500 , quality: 70}
                wide:   { width: 1000 , quality: 90}
        news:
            providers:
                - sonata.media.provider.file
                # - sonata.media.provider.dailymotion
                - sonata.media.provider.youtube
                - sonata.media.provider.image
            formats:
                small: { width: 150 , quality: 95}
                medium: { width: 350 , quality: 95}
                big:   { width: 500 , quality: 90}
                wide:   { width: 1000 , quality: 90}

    cdn:
        server:
            path: /upload/media

    filesystem:
        local:
            # Directory for uploads should be writable
            directory: "%kernel.project_dir%/public/upload/media"
            create: false