sylius_shop:
    resource: "@SyliusShopBundle/Resources/config/routing.yml"
    prefix: /{_locale}
    requirements:
        _locale: ^[A-Za-z]{2,4}(_([A-Za-z]{4}|[0-9]{3}))?(_([A-Za-z]{2}|[0-9]{3}))?$

sylius_shop_payum:
    resource: "@SyliusShopBundle/Resources/config/routing/payum.yml"

sylius_shop_default_locale:
    path: /
    methods: [GET]
    defaults:
        _controller: sylius.controller.shop.locale_switch:switchAction

sylius_shop_available_locales:
    path: /available_locales
    methods: [GET]
    defaults:
        _controller: app.controller.maincontroller:get_available_locales

sylius_shop_available_admins:
    path: /available_admins
    methods: [GET]
    defaults:
        _controller: app.controller.maincontroller:get_available_admins

sylius_shop_support_channels:
    path: /support_channels
    methods: [GET]
    defaults:
        _controller: app.controller.maincontroller:support_channels