<?php

namespace Application\Sonata\UserBundle\Entity;

// use Sonata\UserBundle\Entity\BaseUser as BaseUser;
use App\Entity\User\ShopUser as BaseUser;

/**
 * This file has been generated by the SonataEasyExtendsBundle.
 *
 * @link https://sonata-project.org/easy-extends
 *
 * References:
 * @link http://www.doctrine-project.org/projects/orm/2.0/docs/reference/working-with-objects/en
 */
class User extends BaseUser
{
}
